import { createColumn, createRow, emptyAssignment, type ColumnKind, type SizeChart } from "./chart";
import { createId } from "./ids";
import { isBodyMeasure, type MeasureKey } from "./measures";
import { hasFeature, type PlanId } from "./plans";
import type { LengthUnit, WeightUnit } from "./units";

/**
 * Ready-made charts. Values are typical measurements for EU / US / UK sizing,
 * meant as a starting point: merchants adjust them to their brand.
 * Templates marked `essential` are on every plan; the rest need Pro.
 */

interface TemplateColumn {
  label: string;
  kind: ColumnKind;
  measure?: MeasureKey;
}

export const TEMPLATE_GROUPS = [
  "Women",
  "Men",
  "Unisex",
  "Kids & baby",
  "Footwear",
  "Lingerie & swim",
  "Accessories",
  "Jewellery",
  "Sports",
  "Pets",
  "Home",
  "Start fresh",
] as const;
export type TemplateGroup = (typeof TEMPLATE_GROUPS)[number];

export interface ChartTemplate {
  key: string;
  name: string;
  group: TemplateGroup;
  description: string;
  title: string;
  unit: LengthUnit;
  weightUnit?: WeightUnit;
  columns: TemplateColumn[];
  rows: string[][];
  note: string;
  /** Available on the Free plan. */
  essential?: boolean;
}

const size: TemplateColumn = { label: "Size", kind: "size" };
const sized = (label: string): TemplateColumn => ({ label, kind: "size" });
const m = (label: string, measure: MeasureKey): TemplateColumn => ({ label, kind: "measure", measure });
const t = (label: string): TemplateColumn => ({ label, kind: "text" });

const BETWEEN = "Between sizes? Choose the larger size for a relaxed fit.";
const FEET = "Measure your feet in the evening, when they are at their largest.";

export const TEMPLATES: readonly ChartTemplate[] = [
  // Women
  {
    key: "womens-tops",
    name: "Women's tops & dresses",
    group: "Women",
    essential: true,
    description: "Bust, waist and hips for XS–XXL.",
    title: "Women's size chart",
    unit: "cm",
    columns: [size, m("Bust", "bust"), m("Waist", "waist"), m("Hips", "hips")],
    rows: [
      ["XS", "80–84", "62–66", "86–90"],
      ["S", "84–88", "66–70", "90–94"],
      ["M", "88–92", "70–74", "94–98"],
      ["L", "92–98", "74–80", "98–104"],
      ["XL", "98–104", "80–86", "104–110"],
      ["XXL", "104–110", "86–92", "110–116"],
    ],
    note: BETWEEN,
  },
  {
    key: "womens-numeric",
    name: "Women's numeric sizes (US, UK, EU)",
    group: "Women",
    description: "US 0–16 with UK, EU, IT and FR equivalents.",
    title: "Women's size chart",
    unit: "cm",
    columns: [sized("US"), t("UK"), t("EU"), t("IT"), t("FR"), m("Bust", "bust"), m("Waist", "waist"), m("Hips", "hips")],
    rows: [
      ["0", "4", "30", "36", "32", "78", "60", "85"],
      ["2", "6", "32", "38", "34", "81", "62", "88"],
      ["4", "8", "34", "40", "36", "84", "65", "91"],
      ["6", "10", "36", "42", "38", "87", "68", "94"],
      ["8", "12", "38", "44", "40", "91", "72", "98"],
      ["10", "14", "40", "46", "42", "95", "76", "102"],
      ["12", "16", "42", "48", "44", "99", "80", "106"],
      ["14", "18", "44", "50", "46", "104", "85", "111"],
      ["16", "20", "46", "52", "48", "109", "90", "116"],
    ],
    note: BETWEEN,
  },
  {
    key: "womens-plus",
    name: "Women's plus sizes",
    group: "Women",
    description: "1X–4X (US 14–28) by bust, waist and hips.",
    title: "Plus size chart",
    unit: "cm",
    columns: [size, t("US"), m("Bust", "bust"), m("Waist", "waist"), m("Hips", "hips")],
    rows: [
      ["1X", "14–16", "108–116", "90–98", "114–122"],
      ["2X", "18–20", "118–126", "100–108", "124–132"],
      ["3X", "22–24", "128–136", "110–118", "134–142"],
      ["4X", "26–28", "138–146", "120–128", "144–152"],
    ],
    note: BETWEEN,
  },
  {
    key: "womens-bottoms",
    name: "Women's trousers & skirts",
    group: "Women",
    essential: true,
    description: "Waist, hips and inseam for XS–XL.",
    title: "Women's trousers",
    unit: "cm",
    columns: [size, m("Waist", "waist"), m("Hips", "hips"), m("Inseam", "inseam")],
    rows: [
      ["XS", "62–66", "86–90", "79"],
      ["S", "66–70", "90–94", "80"],
      ["M", "70–74", "94–98", "81"],
      ["L", "74–80", "98–104", "82"],
      ["XL", "80–86", "104–110", "83"],
    ],
    note: "Inseam is for the regular length.",
  },
  {
    key: "womens-jeans",
    name: "Women's jeans (waist sizes)",
    group: "Women",
    description: "Waist sizes 24–34 with hips.",
    title: "Women's jeans",
    unit: "cm",
    columns: [sized("Waist size"), m("Waist", "waist"), m("Hips", "hips")],
    rows: [
      ["24", "61", "86"],
      ["25", "63.5", "88.5"],
      ["26", "66", "91"],
      ["27", "68.5", "93.5"],
      ["28", "71", "96"],
      ["29", "73.5", "98.5"],
      ["30", "76", "101"],
      ["31", "78.5", "103.5"],
      ["32", "81", "106"],
      ["34", "86", "111"],
    ],
    note: "The size is your waist in inches.",
  },
  {
    key: "womens-height-weight",
    name: "Women's quick fit (height & weight)",
    group: "Women",
    description: "Sizes by height and weight, no tape measure needed.",
    title: "Find your size",
    unit: "cm",
    weightUnit: "kg",
    columns: [size, m("Height", "height"), m("Weight", "weight")],
    rows: [
      ["XS", "150–158", "42–50"],
      ["S", "156–164", "48–57"],
      ["M", "162–170", "55–65"],
      ["L", "166–174", "63–74"],
      ["XL", "170–178", "72–84"],
    ],
    note: "A quick guide. For the closest fit, compare your bust, waist and hips.",
  },
  {
    key: "maternity",
    name: "Maternity",
    group: "Women",
    description: "Bust, belly and hips during pregnancy.",
    title: "Maternity size chart",
    unit: "cm",
    columns: [size, m("Bust", "bust"), m("Belly", "waist"), m("Hips", "hips")],
    rows: [
      ["XS", "84–88", "86–92", "90–94"],
      ["S", "88–92", "90–96", "94–98"],
      ["M", "92–96", "94–100", "98–102"],
      ["L", "96–102", "98–106", "102–108"],
      ["XL", "102–108", "104–112", "108–114"],
    ],
    note: "Choose your pre-pregnancy size.",
  },
  {
    key: "womens-activewear",
    name: "Women's activewear",
    group: "Women",
    description: "Leggings and sports tops, XS–XL.",
    title: "Activewear size chart",
    unit: "cm",
    columns: [size, m("Bust", "bust"), m("Waist", "waist"), m("Hips", "hips"), m("Inseam", "inseam")],
    rows: [
      ["XS", "78–82", "60–64", "84–88", "68"],
      ["S", "82–87", "64–68", "88–93", "69"],
      ["M", "87–92", "68–73", "93–98", "70"],
      ["L", "92–98", "73–79", "98–104", "71"],
      ["XL", "98–104", "79–85", "104–110", "72"],
    ],
    note: "Compression fit. Between sizes, choose the larger size.",
  },
  {
    key: "womens-petite",
    name: "Women's petite",
    group: "Women",
    description: "Petite sizes for 1.60 m and under.",
    title: "Petite size chart",
    unit: "cm",
    columns: [size, m("Bust", "bust"), m("Waist", "waist"), m("Hips", "hips"), m("Height", "height")],
    rows: [
      ["XS", "78–82", "60–64", "84–88", "148–160"],
      ["S", "82–86", "64–68", "88–92", "148–160"],
      ["M", "86–90", "68–72", "92–96", "148–160"],
      ["L", "90–96", "72–78", "96–102", "148–160"],
      ["XL", "96–102", "78–84", "102–108", "148–160"],
    ],
    note: "Petite styles have shorter sleeves, bodices and legs.",
  },
  {
    key: "dresses-flat",
    name: "Dresses (garment measurements)",
    group: "Women",
    description: "Laid-flat chest, waist and length of the dress.",
    title: "Dress measurements",
    unit: "cm",
    columns: [size, m("Chest width", "garment_chest"), m("Waist width", "garment_waist"), m("Length", "garment_length")],
    rows: [
      ["XS", "43", "34", "102"],
      ["S", "45", "36", "104"],
      ["M", "47.5", "38.5", "106"],
      ["L", "50.5", "41.5", "108"],
      ["XL", "53.5", "44.5", "110"],
    ],
    note: "Measured flat across the front. Double the widths for the full circumference.",
  },

  // Men
  {
    key: "mens-tops",
    name: "Men's tops & shirts",
    group: "Men",
    essential: true,
    description: "Chest, waist and neck for XS–XXL.",
    title: "Men's size chart",
    unit: "cm",
    columns: [size, m("Chest", "chest"), m("Waist", "waist"), m("Neck", "neck")],
    rows: [
      ["XS", "80–88", "65–73", "35–36"],
      ["S", "88–96", "73–81", "37–38"],
      ["M", "96–104", "81–89", "39–40"],
      ["L", "104–112", "89–97", "41–42"],
      ["XL", "112–124", "97–109", "43–44"],
      ["XXL", "124–136", "109–121", "45–46"],
    ],
    note: BETWEEN,
  },
  {
    key: "mens-shirts",
    name: "Men's dress shirts (collar)",
    group: "Men",
    description: "Collar sizes in cm and inches with sleeve length.",
    title: "Shirt sizes",
    unit: "cm",
    columns: [size, m("Collar", "neck"), t("Collar (US)"), m("Chest", "chest"), m("Sleeve", "arm")],
    rows: [
      ["S", "37–38", "14½–15", "92–97", "84"],
      ["M", "39–40", "15½–16", "98–103", "86"],
      ["L", "41–42", "16½", "104–109", "88"],
      ["XL", "43–44", "17–17½", "110–117", "90"],
      ["XXL", "45–46", "18", "118–125", "92"],
    ],
    note: "Collar is the size that matters most for a dress shirt.",
  },
  {
    key: "mens-suits",
    name: "Men's suits & blazers",
    group: "Men",
    description: "US 36R–48R with EU sizes, chest and waist.",
    title: "Suit sizes",
    unit: "cm",
    columns: [sized("US / UK"), t("EU"), m("Chest", "chest"), m("Waist", "waist")],
    rows: [
      ["36R", "46", "89–92", "74–77"],
      ["38R", "48", "94–97", "79–82"],
      ["40R", "50", "99–102", "84–87"],
      ["42R", "52", "104–107", "89–92"],
      ["44R", "54", "109–112", "94–97"],
      ["46R", "56", "114–117", "99–102"],
      ["48R", "58", "119–122", "104–107"],
    ],
    note: "R is regular length. Short (S) and long (L) fits are on request.",
  },
  {
    key: "mens-bottoms",
    name: "Men's trousers & jeans",
    group: "Men",
    essential: true,
    description: "Waist sizes 28–40 with hips.",
    title: "Men's trousers",
    unit: "cm",
    columns: [sized("Waist size"), m("Waist", "waist"), m("Hips", "hips")],
    rows: [
      ["28", "71–73", "88–90"],
      ["30", "76–78", "93–95"],
      ["32", "81–83", "98–100"],
      ["34", "86–88", "103–105"],
      ["36", "91–93", "108–110"],
      ["38", "97–99", "113–115"],
      ["40", "102–104", "118–120"],
    ],
    note: "The size is your waist in inches.",
  },
  {
    key: "mens-leg-length",
    name: "Trouser lengths (inseam)",
    group: "Men",
    description: "Short, regular and long by inseam and height.",
    title: "Trouser length",
    unit: "cm",
    columns: [sized("Length"), m("Inseam", "inseam"), m("Your height", "height")],
    rows: [
      ["Short (30)", "76", "165–172"],
      ["Regular (32)", "81", "173–180"],
      ["Long (34)", "86", "181–188"],
      ["Extra long (36)", "91", "189–196"],
    ],
    note: "",
  },
  {
    key: "mens-height-weight",
    name: "Men's quick fit (height & weight)",
    group: "Men",
    description: "Sizes by height and weight, no tape measure needed.",
    title: "Find your size",
    unit: "cm",
    weightUnit: "kg",
    columns: [size, m("Height", "height"), m("Weight", "weight")],
    rows: [
      ["S", "165–172", "55–65"],
      ["M", "170–178", "65–75"],
      ["L", "176–184", "75–85"],
      ["XL", "182–190", "85–98"],
      ["XXL", "186–196", "98–110"],
    ],
    note: "A quick guide. For the closest fit, compare your chest and waist.",
  },
  {
    key: "mens-big-tall",
    name: "Men's big & tall",
    group: "Men",
    description: "2XL–5XL, regular and tall lengths.",
    title: "Big & tall size chart",
    unit: "cm",
    columns: [size, m("Chest", "chest"), m("Waist", "waist"), m("Height", "height")],
    rows: [
      ["2XL", "122–127", "107–112", "175–185"],
      ["3XL", "127–132", "112–117", "175–185"],
      ["4XL", "132–137", "117–122", "175–185"],
      ["2XLT", "122–127", "107–112", "185–198"],
      ["3XLT", "127–132", "112–117", "185–198"],
      ["4XLT", "132–137", "117–122", "185–198"],
      ["5XLT", "137–145", "122–130", "185–198"],
    ],
    note: "Tall sizes (T) add about 5 cm to body and sleeve length.",
  },

  // Unisex
  {
    key: "unisex-tops",
    name: "Unisex tops",
    group: "Unisex",
    essential: true,
    description: "XS–3XL by chest and waist.",
    title: "Unisex size chart",
    unit: "cm",
    columns: [size, m("Chest", "chest"), m("Waist", "waist")],
    rows: [
      ["XS", "81–86", "66–71"],
      ["S", "86–94", "71–79"],
      ["M", "94–102", "79–87"],
      ["L", "102–110", "87–95"],
      ["XL", "110–118", "95–103"],
      ["2XL", "118–126", "103–111"],
      ["3XL", "126–134", "111–119"],
    ],
    note: BETWEEN,
  },
  {
    key: "tshirt-flat",
    name: "T-shirts (garment measurements)",
    group: "Unisex",
    essential: true,
    description: "Flat chest width and body length, ideal for print-on-demand.",
    title: "T-shirt measurements",
    unit: "cm",
    columns: [size, m("Chest width", "garment_chest"), m("Body length", "garment_length"), m("Sleeve", "sleeve")],
    rows: [
      ["S", "46", "71", "20"],
      ["M", "51", "74", "21"],
      ["L", "56", "76", "22"],
      ["XL", "61", "79", "23"],
      ["2XL", "66", "81", "24"],
      ["3XL", "71", "84", "25"],
    ],
    note: "Measurements are of the garment laid flat. Tolerance ±2 cm.",
  },
  {
    key: "hoodie-flat",
    name: "Hoodies & sweatshirts (garment)",
    group: "Unisex",
    description: "Flat chest width, body length and sleeve.",
    title: "Hoodie measurements",
    unit: "cm",
    columns: [size, m("Chest width", "garment_chest"), m("Body length", "garment_length"), m("Sleeve", "sleeve")],
    rows: [
      ["S", "53", "69", "62"],
      ["M", "56", "71", "63"],
      ["L", "59", "74", "64"],
      ["XL", "62", "76", "65"],
      ["2XL", "65", "79", "66"],
      ["3XL", "68", "81", "67"],
    ],
    note: "Measurements are of the garment laid flat. Tolerance ±2 cm.",
  },
  {
    key: "joggers-flat",
    name: "Joggers & sweatpants (garment)",
    group: "Unisex",
    description: "Flat waist, hip width and inside leg.",
    title: "Jogger measurements",
    unit: "cm",
    columns: [size, m("Waist width", "garment_waist"), m("Hip width", "garment_hips"), m("Inside leg", "garment_inseam")],
    rows: [
      ["S", "34", "52", "76"],
      ["M", "36", "54", "77"],
      ["L", "38", "56", "78"],
      ["XL", "41", "59", "79"],
      ["2XL", "44", "62", "80"],
    ],
    note: "Waist is measured relaxed; the elastic stretches further.",
  },
  {
    key: "jeans-flat",
    name: "Jeans (garment measurements)",
    group: "Unisex",
    description: "Laid-flat waist, hips, rise and inside leg.",
    title: "Jeans measurements",
    unit: "cm",
    columns: [sized("Waist size"), m("Waist width", "garment_waist"), m("Hip width", "garment_hips"), m("Front rise", "rise"), m("Inside leg", "garment_inseam")],
    rows: [
      ["28", "37", "47", "25", "81"],
      ["30", "39.5", "49.5", "26", "81"],
      ["32", "42", "52", "27", "82"],
      ["34", "44.5", "54.5", "28", "82"],
      ["36", "47", "57", "29", "83"],
    ],
    note: "Compare with a pair of jeans that fits you well, laid flat.",
  },
  {
    key: "womens-international",
    name: "International sizes (women)",
    group: "Unisex",
    description: "XS–XL across US, UK, EU, IT, FR, JP and AU.",
    title: "International size conversion",
    unit: "cm",
    columns: [size, t("US"), t("UK"), t("EU"), t("IT"), t("FR"), t("JP"), t("AU")],
    rows: [
      ["XS", "2", "6", "34", "38", "34", "7", "6"],
      ["S", "4–6", "8–10", "36–38", "40–42", "36–38", "9–11", "8–10"],
      ["M", "8–10", "12–14", "40–42", "44–46", "40–42", "13–15", "12–14"],
      ["L", "12–14", "16–18", "44–46", "48–50", "44–46", "17–19", "16–18"],
      ["XL", "16–18", "20–22", "48–50", "52–54", "48–50", "21–23", "20–22"],
    ],
    note: "Sizes vary between brands; use this as a guide.",
  },
  {
    key: "mens-international",
    name: "International sizes (men)",
    group: "Unisex",
    description: "S–XXL across US, UK, EU, IT and JP.",
    title: "International size conversion",
    unit: "cm",
    columns: [size, t("US"), t("UK"), t("EU"), t("IT"), t("JP")],
    rows: [
      ["S", "36", "36", "46", "46", "S"],
      ["M", "38–40", "38–40", "48–50", "48–50", "M"],
      ["L", "42", "42", "52", "52", "L"],
      ["XL", "44", "44", "54", "54", "LL"],
      ["XXL", "46", "46", "56", "56", "3L"],
    ],
    note: "Sizes vary between brands; use this as a guide.",
  },

  // Kids & baby
  {
    key: "baby",
    name: "Baby (0–24 months)",
    group: "Kids & baby",
    description: "By age, height and weight.",
    title: "Baby size chart",
    unit: "cm",
    weightUnit: "kg",
    columns: [sized("Age"), m("Height", "height"), m("Weight", "weight")],
    rows: [
      ["Newborn", "50–56", "2.5–4.5"],
      ["0–3 M", "56–62", "4–6"],
      ["3–6 M", "62–68", "6–8"],
      ["6–9 M", "68–74", "8–9.5"],
      ["9–12 M", "74–80", "9.5–11"],
      ["12–18 M", "80–86", "11–12.5"],
      ["18–24 M", "86–92", "12.5–14"],
    ],
    note: "Babies grow fast: if in doubt, size up.",
  },
  {
    key: "kids",
    name: "Kids' clothing",
    group: "Kids & baby",
    essential: true,
    description: "Ages 2–12 by height, chest and waist.",
    title: "Kids' size chart",
    unit: "cm",
    columns: [sized("Age"), m("Height", "height"), m("Chest", "chest"), m("Waist", "waist")],
    rows: [
      ["2–3 Y", "92–98", "52–54", "50–52"],
      ["3–4 Y", "98–104", "54–56", "51–53"],
      ["4–5 Y", "104–110", "56–58", "52–54"],
      ["5–6 Y", "110–116", "58–60", "53–55"],
      ["7–8 Y", "122–128", "62–65", "55–57"],
      ["9–10 Y", "134–140", "67–70", "57–60"],
      ["11–12 Y", "146–152", "73–76", "60–63"],
    ],
    note: "Children grow fast: if in doubt, size up.",
  },
  {
    key: "kids-height-weight",
    name: "Kids by height & weight (EU sizes)",
    group: "Kids & baby",
    description: "EU sizes 98–152 by height and weight.",
    title: "Kids' size chart",
    unit: "cm",
    weightUnit: "kg",
    columns: [sized("EU size"), t("Age"), m("Height", "height"), m("Weight", "weight")],
    rows: [
      ["98", "2–3 Y", "93–98", "14–16"],
      ["104", "3–4 Y", "99–104", "16–18"],
      ["110", "4–5 Y", "105–110", "18–20"],
      ["116", "5–6 Y", "111–116", "20–22"],
      ["122", "6–7 Y", "117–122", "22–24"],
      ["128", "7–8 Y", "123–128", "24–27"],
      ["134", "8–9 Y", "129–134", "27–30"],
      ["140", "9–10 Y", "135–140", "30–34"],
      ["146", "10–11 Y", "141–146", "34–38"],
      ["152", "11–12 Y", "147–152", "38–42"],
    ],
    note: "The EU size is the child's height in centimetres.",
  },
  {
    key: "toddler",
    name: "Toddler (US 2T–5T)",
    group: "Kids & baby",
    description: "US toddler sizes by height, weight and chest.",
    title: "Toddler size chart",
    unit: "in",
    weightUnit: "lb",
    columns: [size, m("Height", "height"), m("Weight", "weight"), m("Chest", "chest")],
    rows: [
      ["2T", "33.5–35", "28–30", "21"],
      ["3T", "35.5–38", "31–33", "22"],
      ["4T", "38.5–41", "34–38", "23"],
      ["5T", "41.5–44", "39–42", "24"],
    ],
    note: "Height matters most. If your child is between sizes, choose the larger one.",
  },
  {
    key: "teens",
    name: "Teens (12–16 years)",
    group: "Kids & baby",
    description: "By height, chest and waist.",
    title: "Teen size chart",
    unit: "cm",
    columns: [sized("Age"), m("Height", "height"), m("Chest", "chest"), m("Waist", "waist")],
    rows: [
      ["12 Y", "146–152", "76–79", "62–64"],
      ["13 Y", "152–158", "79–82", "64–66"],
      ["14 Y", "158–164", "82–85", "66–68"],
      ["15 Y", "164–170", "85–88", "68–70"],
      ["16 Y", "170–176", "88–92", "70–73"],
    ],
    note: "",
  },

  // Footwear
  {
    key: "womens-shoes",
    name: "Women's shoes",
    group: "Footwear",
    essential: true,
    description: "EU, US and UK sizes with foot length.",
    title: "Women's shoe sizes",
    unit: "cm",
    columns: [sized("EU"), t("US"), t("UK"), m("Foot length", "foot_length")],
    rows: [
      ["35", "5", "2.5", "22"],
      ["36", "6", "3.5", "22.9"],
      ["37", "6.5", "4", "23.5"],
      ["38", "7.5", "5", "24.1"],
      ["39", "8.5", "6", "24.8"],
      ["40", "9", "6.5", "25.4"],
      ["41", "10", "7.5", "26"],
      ["42", "10.5", "8", "26.7"],
    ],
    note: FEET,
  },
  {
    key: "mens-shoes",
    name: "Men's shoes",
    group: "Footwear",
    essential: true,
    description: "EU, US and UK sizes with foot length.",
    title: "Men's shoe sizes",
    unit: "cm",
    columns: [sized("EU"), t("US"), t("UK"), m("Foot length", "foot_length")],
    rows: [
      ["40", "7", "6", "25.1"],
      ["41", "8", "7", "25.9"],
      ["42", "8.5", "7.5", "26.7"],
      ["43", "9.5", "8.5", "27.3"],
      ["44", "10.5", "9.5", "28.3"],
      ["45", "11.5", "10.5", "29"],
      ["46", "12", "11", "29.4"],
    ],
    note: FEET,
  },
  {
    key: "unisex-sneakers",
    name: "Unisex sneakers",
    group: "Footwear",
    description: "EU 36–46 with US men's, US women's and UK sizes.",
    title: "Sneaker sizes",
    unit: "cm",
    columns: [sized("EU"), t("US men"), t("US women"), t("UK"), m("Foot length", "foot_length")],
    rows: [
      ["36", "4", "5.5", "3.5", "22.5"],
      ["37", "5", "6.5", "4.5", "23.5"],
      ["38", "5.5", "7", "5", "24"],
      ["39", "6.5", "8", "6", "24.5"],
      ["40", "7", "8.5", "6.5", "25"],
      ["41", "8", "9.5", "7.5", "26"],
      ["42", "8.5", "10", "8", "26.5"],
      ["43", "9.5", "11", "9", "27.5"],
      ["44", "10", "11.5", "9.5", "28"],
      ["45", "11", "12.5", "10.5", "29"],
      ["46", "12", "13.5", "11", "29.5"],
    ],
    note: FEET,
  },
  {
    key: "kids-shoes",
    name: "Kids' shoes",
    group: "Footwear",
    description: "EU 20–35 with US and UK sizes and foot length.",
    title: "Kids' shoe sizes",
    unit: "cm",
    columns: [sized("EU"), t("US"), t("UK"), m("Foot length", "foot_length")],
    rows: [
      ["20", "4.5C", "4", "12.2"],
      ["22", "6C", "5.5", "13.5"],
      ["24", "7.5C", "7", "14.9"],
      ["26", "9C", "8.5", "16.2"],
      ["28", "10.5C", "10", "17.5"],
      ["30", "12C", "11.5", "18.8"],
      ["32", "13.5C", "13", "20.1"],
      ["34", "2Y", "1.5", "21.4"],
      ["35", "3Y", "2.5", "22"],
    ],
    note: "Leave about 1 cm of room for growing feet.",
  },
  {
    key: "boots-calf",
    name: "Boots (calf width)",
    group: "Footwear",
    description: "Shaft widths by calf circumference.",
    title: "Boot calf widths",
    unit: "cm",
    columns: [sized("Shaft"), m("Calf", "calf")],
    rows: [
      ["Slim", "33–36"],
      ["Regular", "36–39"],
      ["Wide", "39–42"],
      ["Extra wide", "42–45"],
    ],
    note: "",
  },
  {
    key: "socks",
    name: "Socks",
    group: "Footwear",
    description: "S–XL by shoe size and foot length.",
    title: "Sock sizes",
    unit: "cm",
    columns: [size, t("EU shoe"), t("US shoe"), m("Foot length", "foot_length")],
    rows: [
      ["S", "35–38", "5–7", "22–24"],
      ["M", "39–42", "7.5–9.5", "24.5–26.5"],
      ["L", "43–46", "10–12", "27–29"],
      ["XL", "47–50", "12.5–15", "29.5–31.5"],
    ],
    note: "",
  },

  // Lingerie & swim
  {
    key: "bras-band",
    name: "Bras (band size)",
    group: "Lingerie & swim",
    description: "EU and US/UK band sizes by underbust.",
    title: "Bra band sizes",
    unit: "cm",
    columns: [sized("EU band"), t("US / UK band"), m("Underbust", "underbust")],
    rows: [
      ["65", "30", "63–67"],
      ["70", "32", "68–72"],
      ["75", "34", "73–77"],
      ["80", "36", "78–82"],
      ["85", "38", "83–87"],
      ["90", "40", "88–92"],
      ["95", "42", "93–97"],
    ],
    note: "Measure snugly under your bust, with the tape level.",
  },
  {
    key: "bras-cup",
    name: "Bras (cup size)",
    group: "Lingerie & swim",
    description: "Cup size from the difference between bust and underbust.",
    title: "Bra cup sizes",
    unit: "cm",
    columns: [sized("Cup"), m("Bust minus underbust", "other")],
    rows: [
      ["A", "12–14"],
      ["B", "14–16"],
      ["C", "16–18"],
      ["D", "18–20"],
      ["DD / E", "20–22"],
      ["F", "22–24"],
      ["G", "24–26"],
    ],
    note: "Subtract your underbust from your bust measurement.",
  },
  {
    key: "womens-underwear",
    name: "Women's underwear",
    group: "Lingerie & swim",
    description: "XS–XL by waist and hips.",
    title: "Underwear sizes",
    unit: "cm",
    columns: [size, m("Waist", "waist"), m("Hips", "hips")],
    rows: [
      ["XS", "58–62", "84–88"],
      ["S", "62–66", "88–92"],
      ["M", "66–72", "92–98"],
      ["L", "72–78", "98–104"],
      ["XL", "78–84", "104–110"],
    ],
    note: "",
  },
  {
    key: "womens-swim",
    name: "Women's swimwear",
    group: "Lingerie & swim",
    description: "XS–XL by bust, waist and hips.",
    title: "Swimwear sizes",
    unit: "cm",
    columns: [size, m("Bust", "bust"), m("Waist", "waist"), m("Hips", "hips")],
    rows: [
      ["XS", "78–82", "60–64", "84–88"],
      ["S", "82–86", "64–68", "88–92"],
      ["M", "86–92", "68–74", "92–98"],
      ["L", "92–98", "74–80", "98–104"],
      ["XL", "98–104", "80–86", "104–110"],
    ],
    note: "Swimwear is snug when dry; between sizes, choose the larger size.",
  },
  {
    key: "mens-underwear",
    name: "Men's underwear & swim",
    group: "Lingerie & swim",
    description: "S–XXL by waist.",
    title: "Men's underwear & swim",
    unit: "cm",
    columns: [size, m("Waist", "waist"), t("Waist (in)")],
    rows: [
      ["S", "73–81", "29–32"],
      ["M", "81–89", "32–35"],
      ["L", "89–97", "35–38"],
      ["XL", "97–109", "38–43"],
      ["XXL", "109–121", "43–48"],
    ],
    note: "",
  },

  // Accessories
  {
    key: "hats",
    name: "Hats",
    group: "Accessories",
    essential: true,
    description: "S–XL by head circumference, with US hat sizes.",
    title: "Hat sizes",
    unit: "cm",
    columns: [size, m("Head", "head"), t("US hat size")],
    rows: [
      ["S", "54–55", "6¾–6⅞"],
      ["M", "56–57", "7–7⅛"],
      ["L", "58–59", "7¼–7⅜"],
      ["XL", "60–61", "7½–7⅝"],
    ],
    note: "",
  },
  {
    key: "caps",
    name: "Caps (adjustable)",
    group: "Accessories",
    description: "Two fitted ranges for caps.",
    title: "Cap sizes",
    unit: "cm",
    columns: [size, m("Head", "head")],
    rows: [
      ["S/M", "54–58"],
      ["L/XL", "58–62"],
    ],
    note: "",
  },
  {
    key: "gloves",
    name: "Gloves",
    group: "Accessories",
    description: "S–XL by hand circumference.",
    title: "Glove sizes",
    unit: "cm",
    columns: [size, m("Hand", "hand")],
    rows: [
      ["S", "17–19"],
      ["M", "19–21"],
      ["L", "21–23"],
      ["XL", "23–25"],
    ],
    note: "",
  },
  {
    key: "belts",
    name: "Belts",
    group: "Accessories",
    description: "Belt sizes by waist, with US sizes.",
    title: "Belt sizes",
    unit: "cm",
    columns: [sized("Belt size"), m("Waist", "waist"), t("US")],
    rows: [
      ["75", "70–75", "30"],
      ["80", "75–80", "32"],
      ["85", "80–85", "34"],
      ["90", "85–90", "36"],
      ["95", "90–95", "38"],
      ["100", "95–100", "40"],
      ["105", "100–105", "42"],
      ["110", "105–110", "44"],
    ],
    note: "Choose one size up from your trouser waist size.",
  },
  {
    key: "watch-straps",
    name: "Watch straps",
    group: "Accessories",
    description: "Strap sizes by wrist circumference.",
    title: "Watch strap sizes",
    unit: "cm",
    columns: [size, m("Wrist", "wrist")],
    rows: [
      ["S", "14–16"],
      ["M", "16–18"],
      ["L", "18–20"],
      ["XL", "20–22"],
    ],
    note: "",
  },

  // Jewellery
  {
    key: "rings",
    name: "Rings",
    group: "Jewellery",
    description: "US 4–13 with UK, EU, diameter and circumference in mm.",
    title: "Ring sizes",
    unit: "mm",
    columns: [sized("US"), t("UK"), t("EU"), m("Inside diameter", "ring_diameter"), m("Finger", "finger")],
    rows: [
      ["4", "H", "46.5", "14.9", "46.8"],
      ["5", "J½", "49.3", "15.7", "49.3"],
      ["6", "L½", "51.9", "16.5", "51.9"],
      ["7", "N½", "54.4", "17.3", "54.4"],
      ["8", "P½", "57", "18.1", "57"],
      ["9", "R½", "59.5", "18.9", "59.5"],
      ["10", "T½", "62.1", "19.8", "62.1"],
      ["11", "V½", "64.6", "20.6", "64.6"],
      ["12", "X½", "67.2", "21.4", "67.2"],
      ["13", "Z½", "69.7", "22.2", "69.7"],
    ],
    note: "Fingers are slightly larger in warm weather. Between sizes, choose the larger size.",
  },
  {
    key: "bracelets",
    name: "Bracelets",
    group: "Jewellery",
    description: "Bracelet lengths by wrist size.",
    title: "Bracelet sizes",
    unit: "cm",
    columns: [size, m("Wrist", "wrist"), m("Bracelet length", "other")],
    rows: [
      ["XS", "14–15", "16"],
      ["S", "15–16", "17"],
      ["M", "16–17", "18"],
      ["L", "17–18", "19"],
      ["XL", "18–19", "20"],
    ],
    note: "",
  },
  {
    key: "necklaces",
    name: "Necklace lengths",
    group: "Jewellery",
    description: "Collar to rope lengths and where they sit.",
    title: "Necklace lengths",
    unit: "cm",
    columns: [sized("Style"), m("Length", "other"), t("Sits at")],
    rows: [
      ["Collar", "35", "Base of the neck"],
      ["Choker", "40", "Just above the collarbone"],
      ["Princess", "45", "On the collarbone"],
      ["Matinee", "55", "Above the bust"],
      ["Opera", "75", "At or below the bust"],
      ["Rope", "90", "Below the bust; can be doubled"],
    ],
    note: "",
  },

  // Sports
  {
    key: "cycling-helmets",
    name: "Helmets",
    group: "Sports",
    description: "S–L by head circumference.",
    title: "Helmet sizes",
    unit: "cm",
    columns: [size, m("Head", "head")],
    rows: [
      ["S", "51–55"],
      ["M", "55–59"],
      ["L", "59–63"],
    ],
    note: "A helmet should sit level and not move when you shake your head.",
  },
  {
    key: "wetsuits",
    name: "Wetsuits",
    group: "Sports",
    description: "By height, weight and chest.",
    title: "Wetsuit sizes",
    unit: "cm",
    weightUnit: "kg",
    columns: [size, m("Height", "height"), m("Weight", "weight"), m("Chest", "chest")],
    rows: [
      ["S", "165–172", "60–68", "88–94"],
      ["M", "170–178", "68–77", "94–100"],
      ["L", "176–184", "77–86", "100–106"],
      ["XL", "182–190", "86–95", "106–112"],
    ],
    note: "A wetsuit should feel snug everywhere without restricting your breathing.",
  },
  {
    key: "sports-bras",
    name: "Sports bras",
    group: "Sports",
    description: "XS–XL by underbust and bust.",
    title: "Sports bra size chart",
    unit: "cm",
    columns: [size, m("Underbust", "underbust"), m("Bust", "bust"), t("Cup sizes")],
    rows: [
      ["XS", "63–67", "76–80", "A–C"],
      ["S", "68–72", "81–86", "A–D"],
      ["M", "73–77", "87–92", "B–D"],
      ["L", "78–82", "93–98", "B–DD"],
      ["XL", "83–87", "99–105", "C–DD"],
    ],
    note: "For high-impact sports, choose the size that fits your underbust snugly.",
  },
  {
    key: "leggings",
    name: "Leggings & yoga pants",
    group: "Sports",
    description: "Waist, hips and inside leg, XS–XL.",
    title: "Leggings size chart",
    unit: "cm",
    columns: [size, m("Waist", "waist"), m("Hips", "hips"), m("Inside leg", "inseam")],
    rows: [
      ["XS", "60–64", "84–88", "69"],
      ["S", "64–68", "88–93", "70"],
      ["M", "68–73", "93–98", "71"],
      ["L", "73–79", "98–104", "72"],
      ["XL", "79–85", "104–110", "72"],
    ],
    note: "Made to stretch: choose your usual size for a sculpting fit.",
  },
  {
    key: "ski-boots",
    name: "Ski boots (Mondopoint)",
    group: "Sports",
    description: "Mondopoint sizes by foot length, with EU sizes.",
    title: "Ski boot sizes",
    unit: "cm",
    columns: [sized("Mondopoint"), t("EU"), m("Foot length", "foot_length")],
    rows: [
      ["23.5", "37", "23.1–23.5"],
      ["24.5", "38.5", "24.1–24.5"],
      ["25.5", "40", "25.1–25.5"],
      ["26.5", "41.5", "26.1–26.5"],
      ["27.5", "43", "27.1–27.5"],
      ["28.5", "44.5", "28.1–28.5"],
      ["29.5", "46", "29.1–29.5"],
    ],
    note: "Mondopoint is your foot length in centimetres.",
  },

  // Pets
  {
    key: "pets",
    name: "Dog coats & sweaters",
    group: "Pets",
    essential: true,
    description: "Neck, chest and back length for dogs and cats.",
    title: "Pet size chart",
    unit: "cm",
    columns: [size, m("Neck", "pet_neck"), m("Chest", "pet_chest"), m("Back length", "pet_back")],
    rows: [
      ["XS", "20–25", "30–35", "20"],
      ["S", "25–30", "35–45", "25"],
      ["M", "30–38", "45–55", "30"],
      ["L", "38–45", "55–65", "40"],
      ["XL", "45–55", "65–75", "50"],
    ],
    note: "Chest is the most important measurement for a comfortable fit.",
  },
  {
    key: "dog-collars",
    name: "Dog collars",
    group: "Pets",
    description: "XS–XL by neck size.",
    title: "Collar sizes",
    unit: "cm",
    columns: [size, m("Neck", "pet_neck"), t("Width")],
    rows: [
      ["XS", "20–25", "1 cm"],
      ["S", "25–32", "1.5 cm"],
      ["M", "32–40", "2 cm"],
      ["L", "40–50", "2.5 cm"],
      ["XL", "50–60", "3 cm"],
    ],
    note: "You should be able to fit two fingers under the collar.",
  },
  {
    key: "dog-harness",
    name: "Dog harnesses",
    group: "Pets",
    description: "By chest, neck and weight.",
    title: "Harness sizes",
    unit: "cm",
    weightUnit: "kg",
    columns: [size, m("Chest", "pet_chest"), m("Neck", "pet_neck"), m("Weight", "pet_weight")],
    rows: [
      ["XS", "30–40", "20–28", "1–4"],
      ["S", "38–50", "26–36", "4–8"],
      ["M", "48–62", "34–46", "8–15"],
      ["L", "60–76", "44–56", "15–30"],
      ["XL", "74–90", "54–66", "30–45"],
    ],
    note: "Chest is the most important measurement. Weight is a guide only.",
  },
  {
    key: "dog-coats",
    name: "Dog coats",
    group: "Pets",
    description: "By back length, chest and neck.",
    title: "Dog coat sizes",
    unit: "cm",
    columns: [size, m("Back length", "pet_back"), m("Chest", "pet_chest"), m("Neck", "pet_neck")],
    rows: [
      ["XS", "25", "32–38", "22–26"],
      ["S", "30", "38–46", "26–32"],
      ["M", "40", "46–56", "32–40"],
      ["L", "50", "56–68", "40–48"],
      ["XL", "60", "68–80", "48–56"],
    ],
    note: "Back length is measured from the base of the neck to the base of the tail.",
  },
  {
    key: "cat-harness",
    name: "Cat harnesses",
    group: "Pets",
    description: "By chest, neck and weight.",
    title: "Cat harness sizes",
    unit: "cm",
    weightUnit: "kg",
    columns: [size, m("Chest", "pet_chest"), m("Neck", "pet_neck"), m("Weight", "pet_weight")],
    rows: [
      ["S", "26–33", "18–24", "1–3"],
      ["M", "31–40", "22–30", "3–5"],
      ["L", "38–48", "28–36", "5–8"],
    ],
    note: "",
  },

  // Home
  {
    key: "duvets",
    name: "Duvets & covers (EU)",
    group: "Home",
    description: "Single to super king.",
    title: "Duvet sizes",
    unit: "cm",
    columns: [sized("Size"), m("Width", "other"), m("Length", "other")],
    rows: [
      ["Single", "135", "200"],
      ["Double", "200", "200"],
      ["King", "230", "220"],
      ["Super king", "260", "220"],
    ],
    note: "",
  },
  {
    key: "mattresses-us",
    name: "Mattresses (US)",
    group: "Home",
    description: "Twin to California king.",
    title: "Mattress sizes",
    unit: "in",
    columns: [sized("Size"), m("Width", "other"), m("Length", "other")],
    rows: [
      ["Twin", "38", "75"],
      ["Twin XL", "38", "80"],
      ["Full", "54", "75"],
      ["Queen", "60", "80"],
      ["King", "76", "80"],
      ["California king", "72", "84"],
    ],
    note: "",
  },

  // Start fresh
  {
    key: "blank",
    name: "Blank chart",
    group: "Start fresh",
    essential: true,
    description: "Start from an empty table with your own columns.",
    title: "Size chart",
    unit: "cm",
    columns: [size, m("Chest", "chest"), m("Waist", "waist")],
    rows: [["S"], ["M"], ["L"]],
    note: "",
  },
];

export function getTemplate(key: string): ChartTemplate | undefined {
  return TEMPLATES.find((template) => template.key === key);
}

export function chartFromTemplate(template: ChartTemplate): SizeChart {
  const columns = template.columns.map((c) => createColumn(c.kind, c.label, c.measure));
  const rows = template.rows.map((values) =>
    createRow(Object.fromEntries(values.map((value, index) => [columns[index]!.id, value]))),
  );
  const hasBodyMeasure = template.columns.some((c) => c.measure !== undefined && isBodyMeasure(c.measure));
  return {
    id: createId("c"),
    name: template.name,
    title: template.title,
    status: "active",
    category: template.key,
    unit: template.unit,
    weightUnit: template.weightUnit ?? "kg",
    columns,
    rows,
    note: template.note,
    guide: { enabled: true, text: "", diagram: "auto" },
    fitFinder: hasBodyMeasure,
    fitScale: null,
    image: null,
    assignment: emptyAssignment("all"),
    translations: {},
  };
}

const CLOTHING_GROUPS: readonly TemplateGroup[] = ["Women", "Men", "Unisex", "Kids & baby"];

/**
 * Which plan feature the Fit Finder needs on a chart: clothing charts made from
 * a women's, men's, unisex or kids' template need Pro, everything else
 * (footwear, lingerie, rings, pets, charts started from scratch) needs Plus.
 */
export function fitFinderFeature(category: string): "fitFinder" | "fitFinderAll" {
  const group = getTemplate(category)?.group;
  return group && CLOTHING_GROUPS.includes(group) ? "fitFinder" : "fitFinderAll";
}

export function fitFinderAllowed(plan: PlanId, category: string): boolean {
  return hasFeature(plan, fitFinderFeature(category));
}

export function templateAllowed(plan: PlanId, template: ChartTemplate): boolean {
  return Boolean(template.essential) || hasFeature(plan, "allTemplates");
}

export const ESSENTIAL_COUNT = TEMPLATES.filter((template) => template.essential).length;
